<a href="https://colab.research.google.com/github/Rixxi21/Data-type-NumPy/blob/main/Tipo_de_datos_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [7]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [12]:
arr

array([1, 2, 3, 4])

In [14]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [15]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [16]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [19]:
arr = np.array(['hola','0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored